#spring:
 # application:name: ORDER-SERVICE

#eureka:
  #client:
    #register-with.client : ture
   # fetch-registry : ture
  #  service-url:defaultZone : http://localhost:8761/erueka/
#  instance:
 #   hostname : localhost

logging:
  file:
    path:
      C:\Users\shubham.wattamwar\springBoot\microservice.log

spring:
  zipkin:
    base-url: http://localhost:9411/

